server:
    port: 8082

spring:
  profiles:
      active: dev

---

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/dcbapp
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    config:
        activate:
            on-profile: dev
welcome:
    message: Welcome to Daily Code Buffer

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/dcbapp_qa
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    config:
        activate:
            on-profile: qa
#welcome:
#    message: Welcome to Daily Code Buffer

---

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/dcbapp_prod
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    config:
        activate:
            on-profile: prod


